### ISSUE TITLE
React does not render on server but is rendered after FOC

### ISSUE THREAD

**Issue by Webkadabra** [wi2/sails-generate-isoreact#1]
Evening! I'm new to Sails, and having such issue: when page is opened, I see for a moment that default homepage is rendered, and only then React component is rendered. React is not being rendered on server side. Could you please advise on where should I start fixing this? Thanks!

**Comment by wi2** [comment]
Hi,
i think you don't add routes in config/routes.js.
Look at the bottom of README an example of routes.

```
'/': 'HomeController.home'
```

You can clone this for testing a simple working example : https://github.com/wi2/isomorphic-sails-react-example

Hope is helpful.. 
Sorry for my broken english..
