### ISSUE TITLE
Make a tutorial?

### ISSUE THREAD

**Issue by kulakowka** [wi2/sails-generate-isoreact#2]
You did a good project. But to understand how it works, it was not easy.

Can you add a more detailed example?

For example: how to make a page with a list of articles and page view the article? 

Maybe you can make tutorial for Flux architecture?

**Comment by wi2** [comment]
Thank you.

Today, i have not really time to making a tutorial. maybe in couple weeks..

But i fastly add some stuff in https://github.com/wi2/isomorphic-sails-react-example

and invite you take a look for mor information about dependencies of this project.
- [React-router](http://rackt.github.io/react-router/)  A complete routing solution for React.js
- [sails-react-store](https://github.com/wi2/sails-react-store) wrapper of sails.socket.io with auto blueprint

Hope is a little bit helpful.. and thank you for your interest..

**Comment by kulakowka** [comment]
Thank you! That's exactly what I wanted.

**Comment by wi2** [comment]
cool..
